// What each tour says, step by step.
//
// Short, and in the voice of someone showing a friend around: what the
// control is and what to do with it, in a sentence or two. Each step names
// the guide step it abbreviates, so when a guide changes the tour is caught
// by the test that reads both. The last step on every page is the (?), where
// the whole story is.

import type { Tour, TourStep } from "./types.ts";

const GUIDE: TourStep = {
  target: "shell.guide",
  title: "The guide",
  says: "The whole story of this page lives behind the (?). Every page has one.",
  side: "bottom", align: "end",
};

/// The one page whose markup belongs to the sign-in package: its field has
/// an id, its two strips have labels, and its two buttons are found by
/// their words until the package carries a tour name of its own.
const byText = (prefix: string) => () =>
  [...document.querySelectorAll("button")].find((b) => (b.textContent ?? "").trim().startsWith(prefix)) ?? null;

export const TOURS: Record<Tour["page"], Tour> = {
  welcome: { page: "welcome", steps: [
    { target: "welcome.signin", title: "Sign in",
      says: "Your Nostr key signs you in. Tap here when you have one; the next page shows where to get one." },
    { target: "welcome.explainers", title: "Read freely",
      says: "How a plant, an insect, a tree and an animal live through a year here. Open any of them as you are.", side: "top" },
    { target: "welcome.guides", title: "The guides",
      says: "Each working page has a guide like these. The (?) on every page opens its own.", side: "top" },
  ]},

  signin: { page: "signin", steps: [
    { target: () => document.getElementById("tb-npub-field"), title: "Your npub",
      says: "Paste your npub here. An nsec works too and stays in this browser." },
    { target: () => document.querySelector('nav[aria-label="Tools for signing in"]'), title: "Get a key",
      says: "Get a free key in 0xchat or Pricing Studio. Either makes one in a minute.", side: "top" },
    { target: byText("Send message"), title: "Send",
      says: "We send a message to your Nostr client. Reply to it with any words." },
    { target: () => document.querySelector('[aria-label="How signing in works"]'), title: "The proof",
      says: "Your signed reply is the proof. The tiles show where you are.", side: "top" },
    { target: byText("I've replied"), title: "Verify",
      says: "Replied? Tap here and you are in." },
  ]},

  ledger: { page: "ledger", steps: [
    { target: "firstrun.here", title: "Start where you are",
      says: "Tap here and your ground is about ten acres around this device, to move and reshape later." },
    { target: "firstrun.draw", title: "Or draw it",
      says: "Trace the field, or drop a pin with a radius, on My Plots." },
    { target: "ledger.chips", title: "The chips", guide: ["Read the season", "The chips by the title"],
      says: "The base, the start of the season and the samples this answer is made from." },
    { target: "ledger.pulse", title: "The pulse", guide: ["Read the season", "The pulse strip"],
      says: "Where the season stands today: heat, frost, soil, drying and disease at a glance." },
    { target: "ledger.chart", title: "The season's heat", guide: ["Read the season", "The chart"],
      says: "Heat accumulated so far against the normal. Tap a mark to open the event behind it.", side: "top" },
    { target: "ledger.ground", title: "Ground", guide: ["Read the season", "🛰️ Ground"],
      says: "Ghosts the satellite's view of your ground behind the curve." },
    { target: "ledger.events", title: "Events", guide: ["Read the season", "🔔 Events"],
      says: "Places your crops, pests and watches where they meet the curve." },
    { target: "ledger.weather", title: "Weather", guide: ["Read the season", "🌦️ Weather"],
      says: "Cycles a weather reading behind the curve. Tap past the last to clear it." },
    { target: "ledger.trends", title: "Trends", guide: ["The trends", "❄️ Freezing"],
      says: "Freezing, soil, drying and disease, each with its own card below.", side: "top" },
    { target: "ledger.doors", title: "More views", guide: ["The trends", "More Views"],
      says: "Doors to the other pages. The rail opens them too.", side: "top" },
    { target: "rail.plots", title: "My Plots",
      says: "Your ground lives here: add a plot, draw it, and every page answers for it.", side: "right" },
    { target: "shell.account", title: "Your account",
      says: "Your balance, your profile and the Live tutorial switch.", side: "bottom", align: "end" },
    GUIDE,
  ]},

  plots: { page: "plots", steps: [
    { target: "plots.add", title: "Add a plot", guide: ["Add ground", "+ Add a plot"],
      says: "Opens the finder and the drawing map. Tap it to add ground." },
    { target: "plots.search", title: "Find the place", before: "open-add-form",
      guide: ["Add ground", "Find a town, road or address · Use my location"],
      says: "Type a town, road or address to bring the map there." },
    { target: "plots.locate", title: "Use my location", guide: ["Add ground", "Find a town, road or address · Use my location"],
      says: "Centres the map on this device." },
    { target: "plots.shape", title: "Trace or pin", guide: ["Add ground", "Trace a block"],
      says: "Trace a block corner by corner, or drop a pin with a radius." },
    { target: "plots.map", title: "The drawing map", guide: ["Add ground", "Pin + radius"],
      says: "Tap the map to set each corner; drag a dot to move it. Three corners make a block.", side: "top" },
    { target: "plots.name", title: "Name", guide: ["Add ground", "Name · Base"],
      says: "A name you will recognise on the chips." },
    { target: "plots.base", title: "Base", guide: ["Add ground", "Name · Base"],
      says: "The temperature heat is counted from. Fifty is usual; change it when you know yours." },
    { target: "plots.save", title: "Save", guide: ["Add ground", "Save"],
      says: "Saves the ground and makes it the plot you are working." },
    { target: "plots.import", title: "Import", guide: ["Add ground", "Import"],
      says: "Brings in a farm bundle another grower shared." },
    { target: "plots.chips", title: "The chips", guide: ["Read and switch", "The chips"],
      says: "One per plot. Tap one to work it; tap it again to frame it on the map." },
    { target: "plots.rename", title: "Rename", guide: ["Change", "The pencil"],
      says: "Renames the plot and keeps its other names." },
    { target: "plots.share", title: "Share", guide: ["Change", "Share"],
      says: "Hands this plot to another grower as a bundle." },
    { target: "plots.forget", title: "Forget", guide: ["Remove", "The bin"],
      says: "Forgets the plot. The record keeps it, and saving it again brings it back." },
    { target: "plots.sun", title: "The Sun", guide: ["Read and switch", "The Sun button"],
      says: "Turns the Sun layer on: hours of sun across the plot, and the best place for panels.", side: "left" },
    { target: "plots.sunview", title: "Garden or Solar", guide: ["Read and switch", "The Sun button"],
      says: "Garden shows hours of light; Solar shows what panels would make. Tap inside the plot for that spot." },
    GUIDE,
  ]},

  crops: { page: "crops", steps: [
    { target: "crops.species", title: "Species", guide: ["Add a planting", "Species"],
      says: "Type a plant's name and pick it from the list. Fungi are here too." },
    { target: "crops.label", title: "Your name for it", guide: ["Add a planting", "Your name for it"],
      says: "Optional. How you will find the row again, like Zinnia · succession 4." },
    { target: "crops.target", title: "GDD target", guide: ["Add a planting", "GDD target · Planted · Base"],
      says: "The heat it needs from set-out to harvest, from the packet or a trial. Blank makes it a perennial." },
    { target: "crops.setout", title: "Planted", guide: ["Add a planting", "GDD target · Planted · Base"],
      says: "The day it was set out or sown. Heat is counted from here." },
    { target: "crops.base", title: "Base", guide: ["Add a planting", "GDD target · Planted · Base"],
      says: "The temperature heat is counted from. Blank takes the plot's." },
    { target: "crops.flower", title: "Flower", guide: ["Add a planting", "Flower · Height · Blooms"],
      says: "Optional, for Design companions: the colour it brings." },
    { target: "crops.height", title: "Height", guide: ["Add a planting", "Flower · Height · Blooms"],
      says: "How tall it grows, in inches, for pairing by height." },
    { target: "crops.blooms", title: "Blooms", guide: ["Add a planting", "Flower · Height · Blooms"],
      says: "The months it is in bloom." },
    { target: "crops.hardy", title: "Handles Light Frost", guide: ["Add a planting", "Handles Light Frost · Sap Producer"],
      says: "Tick it for a plant that can go out before the last frost." },
    { target: "crops.taps", title: "Sap Producer", guide: ["Add a planting", "Handles Light Frost · Sap Producer"],
      says: "Tick it for a tree you tap; the sap run joins the tree year." },
    { target: "crops.add", title: "Planting", guide: ["Add a planting", "+ Planting"],
      says: "Writes the row. One press, one row." },
    { target: "crops.filter", title: "Filter", guide: ["Read the ledger", "The heading"],
      says: "Narrows the ledger: ready before frost, has seed, due within so many days." },
    { target: "crops.search", title: "Search", guide: ["Read the ledger", "The heading"],
      says: "A word or a regular expression, run when you submit it." },
    { target: "crops.ledger", title: "The ledger", guide: ["Read the ledger", "A row"],
      says: "Each planting with its heat to target and its verdict. Tap a row to edit it; its buttons add seed, a harvest, companions, or remove it.", side: "top" },
    { target: "crops.rotation", title: "Rotation", guide: ["Read the ledger", "🔄 Rotation — What grew here?"],
      says: "Every planting this plot has had, by season and family. Tap one to plant it again." },
    { target: "crops.fit", title: "Grows here", guide: ["Read the ledger", "🌾 Grows here"],
      says: "Rates each planting against the plot's frost-free days and heat, the trees on winters survived, and this year's first leaf and bloom." },
    { target: "crops.sow", title: "When to sow", guide: ["Read the ledger", "🌱 When to sow — 🧠 When?"],
      says: "Seed indoors, out, last sowing, and the window between, per planting." },
    { target: "crops.community", title: "Community Observations", guide: ["Add a planting", "Community Observations"],
      says: "What people have recorded growing near here. Tick some and add them in one write." },
    GUIDE,
  ]},

  pests: { page: "pests", steps: [
    { target: "pests.species", title: "Pest", guide: ["Watch a pest", "Pest"],
      says: "Type its name and pick it from the list, or keep what you typed." },
    { target: "pests.base", title: "Base", guide: ["Watch a pest", "Base"],
      says: "The temperature its heat is counted from. Blank takes the plot's." },
    { target: "pests.biofix", title: "Biofix", guide: ["Watch a pest", "Biofix"],
      says: "The day its season starts: first catch, first sighting." },
    { target: "pests.stages", title: "Stages", guide: ["Watch a pest", "Stages"],
      says: "Its stages by heat, like first flight 375, second flight 1400." },
    { target: "pests.add", title: "The bug button", guide: ["Watch a pest", "The bug button"],
      says: "Puts it on your watch list." },
    { target: "pests.active", title: "Active now", guide: ["Read what you're watching", "Active now"],
      says: "The pests whose stage is due this week." },
    { target: "pests.filter", title: "Filter", guide: ["Read what you're watching", "The heading"],
      says: "Narrows the list to what is due soon, what crossed a stage this season, or what you watch by eye." },
    { target: "pests.list", title: "Your watch list", guide: ["Read what you're watching", "A row"],
      says: "Each pest with its biofix, the heat so far and its stages. Tap a row to edit it; the bin removes it.", side: "top" },
    { target: "pests.catalog", title: "When they appear here", guide: ["Watch a pest", "🐛 When they appear here — What's here?"],
      says: "The pests known to this region and when each is due here. Tap one to watch it." },
    { target: "pests.community", title: "Community Observations", guide: ["Watch a pest", "Community Observations"],
      says: "What people have recorded seeing near here. Tick some and add them in one write." },
    GUIDE,
  ]},

  wildlife: { page: "wildlife", steps: [
    { target: "wildlife.species", title: "Species", guide: ["Track something", "The creature"],
      says: "Type a creature's name: your own record, what is seen nearby, or add it as yours." },
    { target: "wildlife.role", title: "Friend, foe or watch", guide: ["Track something", "The creature"],
      says: "How you hold it: a friend to help, a foe to guard against, or something to watch." },
    { target: "wildlife.clock", title: "The clock", guide: ["Track something", "The clock"],
      says: "What times the event: days from a day you saw, your record, daylight, heat, or conditions." },
    { target: "wildlife.label", title: "What it does", guide: ["Track something", "The figures"],
      says: "The event in your words: first arrival, laying, kidding. Suggestions appear below." },
    { target: "wildlife.figures", title: "The figures", guide: ["Track something", "The figures"],
      says: "The clock's numbers: a date and the days that follow, a month and day, hours of daylight, heat and base, or the nights and days it waits for." },
    { target: "wildlife.record", title: "Record", guide: ["Track something", "Save"],
      says: "Writes the watch. The dates it will fall on show above first." },
    { target: "wildlife.due", title: "Due soon", guide: ["Read the year", "Watch for these"],
      says: "What is due in the next while. I saw it records the day; Start another begins the next cycle." },
    { target: "wildlife.list", title: "The year", guide: ["Read the year", "The columns"],
      says: "Every watch with its clock and when it falls. Tap a row to edit it; the bin removes it.", side: "top" },
    { target: "wildlife.community", title: "Community Observations", guide: ["Track something", "Community Observations"],
      says: "What people have recorded seeing near here. Tick some and add them in one write." },
    GUIDE,
  ]},

  reports: { page: "reports", steps: [
    { target: "reports.tags", title: "The tags", guide: ["File one", "The tags"],
      says: "What you saw: frost, first bloom, emergence, a pest, or a note." },
    { target: "reports.custom", title: "Or your own words", guide: ["File one", "The tags"],
      says: "Type what you saw when the tags miss it." },
    { target: "reports.on", title: "Seen on", guide: ["File one", "Seen on"],
      says: "The day you saw it. Today is filled in." },
    { target: "reports.crop", title: "Crop", before: "pick-tag:first_bloom", guide: ["File one", "Crop"],
      says: "The plant it happened to, as you name it." },
    { target: "reports.setout", title: "Set out", guide: ["File one", "Set out · Expected at (GDD)"],
      says: "The day that plant went in, so the heat since can be counted." },
    { target: "reports.target", title: "Expected at", guide: ["File one", "Set out · Expected at (GDD)"],
      says: "The heat it was expected at. The difference teaches the model." },
    { target: "reports.here", title: "Here", guide: ["File one", "Here"],
      says: "Pins the report to this device's location." },
    { target: "reports.add", title: "Observation", guide: ["File one", "Observation"],
      says: "Files it. The bias cards above learn from it." },
    { target: "reports.inat", title: "Import from iNaturalist", guide: ["Import from iNaturalist", "Your handle"],
      says: "Your iNaturalist handle brings in what you have recorded there. Search, tick, import.", side: "top" },
    { target: "reports.log", title: "Log", guide: ["Read what it learned", "Log"],
      says: "Every report you have filed, newest first, each with its bin.", side: "top" },
    GUIDE,
  ]},

  todo: { page: "todo", steps: [
    { target: "todo.title", title: "What needs doing", guide: ["Write one down", "What needs doing · Due"],
      says: "The task, in a few words." },
    { target: "todo.due", title: "Due", guide: ["Write one down", "What needs doing · Due"],
      says: "The day it is due. Optional." },
    { target: "todo.reminder", title: "Reminder only?", guide: ["Write one down", "Reminder only?"],
      says: "Ticked, the task is a day. Untick it to give it a start and an end time." },
    { target: "todo.times", title: "From and To", before: "show-times", guide: ["Write one down", "Reminder only?"],
      says: "The hours it takes, for the calendar feed." },
    { target: "todo.note", title: "Note", guide: ["Write one down", "Note"],
      says: "Where the row cover is, who to call." },
    { target: "todo.add", title: "Task", guide: ["Write one down", "+ Task"],
      says: "Writes it to the list." },
    { target: "todo.gear", title: "The gear", guide: ["Write one down", "The gear"],
      says: "The calendar feed: your tasks in the calendar app on your phone." },
    { target: "todo.frames", title: "Day to All", guide: ["See what is due", "Day · Week · Month · Season · All"],
      says: "How far ahead the list looks." },
    { target: "todo.search", title: "Search", guide: ["See what is due", "Search"],
      says: "A word or a regular expression." },
    { target: "todo.list", title: "The list", guide: ["Change", "The checkbox"],
      says: "Tick the box when it is done; tap a cell to change it; the bin removes it.", side: "top" },
    GUIDE,
  ]},

  almanac: { page: "almanac", steps: [
    { target: "almanac.today", title: "Today", guide: ["Read", "Today"],
      says: "The sky, the wind, the dew point, the rain, sunrise and sunset and the moon, for this plot today." },
    { target: "almanac.radar", title: "Rain on the radar", guide: ["Read", "🌧️ in the title row"],
      says: "Shows the rain radar over the plot, playing the last hour." },
    { target: "almanac.fortnight", title: "The fortnight", guide: ["Read", "The fortnight"],
      says: "Fourteen days ahead, a card each.", side: "top" },
    { target: "almanac.chiclets", title: "The season so far", guide: ["Arrange", "The chiclets"],
      says: "One chart per measure. Tap a chiclet to show or hide it; drag to reorder." },
    { target: "shell.share", title: "Share", guide: ["Read", "Share, in the top bar"],
      says: "Takes the almanac with you, as a table or as JSON.", side: "bottom", align: "end" },
    GUIDE,
  ]},

  account: { page: "account", steps: [
    { target: "account.summary", title: "Your balance",
      says: "Sats on hand and what today has drawn. Top up from here." },
    { target: "account.tutorial", title: "Live tutorial",
      says: "This tour, on every page. Turn it off here or from any popover; turn it on to see it all again." },
    { target: "account.season", title: "Season",
      says: "The colour of the pages follows the calendar, or stays in the season you pick." },
    { target: "account.degrees", title: "Degrees",
      says: "Fahrenheit or Celsius for everything shown. The record keeps what you entered." },
    { target: "account.bees", title: "Foraging bees",
      says: "They fly on warm days. Switch them off for a still page." },
    { target: "account.forget", title: "Forget my ground",
      says: "Removes your plots and everything recorded on them. Your balance stays.", side: "top" },
  ]},
};
